name: Create PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v5

      # Create a Pull Request using GitHub CLI
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Merge Develop into Main"
          body: "This PR was automatically created by GitHub Actions."
          draft: false
          labels: automated-pr